spring.application.name=ecom-application
info.app.name=${spring.application.name}
info.app.description=This is a sample e-commerce application
info.app.version=1.0.0

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
#management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
#management.endpoint.shutdown.enabled=true
#server.shutdown = graceful
management.info.env.enabled=true
